import {test,expect} from '@playwright/test';
test('demo José: intención → propuesta → VOY → confirmado → asistencia → cierre',async({page})=>{
 await page.goto('/');await expect(page.getByRole('heading',{name:/Estoy libre/})).toBeVisible();await page.screenshot({path:'test-results/now-landing-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Probar mi primer NOW'}).click();await expect(page.getByRole('heading',{name:'¿Qué te apetece, José?'})).toBeVisible();
 await page.screenshot({path:'test-results/now-home-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'🍺 Tomar algo'}).click();await page.getByRole('button',{name:'Usar campus de demostración'}).click();await page.getByRole('button',{name:/Una cerveza/}).click();await page.getByRole('button',{name:/2 horas/}).click();await page.getByRole('button',{name:/Mi comunidad/}).click();
 await expect(page.getByRole('heading',{name:'Tomar algo. ¿NOW?'})).toBeVisible();await expect(page.getByText('Conocerás al grupo y el punto exacto cuando todos acepten.')).toBeVisible();
 await page.getByRole('button',{name:'VOY',exact:true}).click();await expect(page.getByRole('heading',{name:'Nos vemos fuera.'})).toBeVisible();await expect(page.getByText('PUNTO DE ENCUENTRO PÚBLICO')).toBeVisible();
 await page.screenshot({path:'test-results/now-confirmed-desktop.png',fullPage:true});await page.getByRole('button',{name:'Estoy aquí',exact:true}).click();await expect(page.getByRole('button',{name:'Ya estás aquí'})).toBeDisabled();
 await page.getByRole('button',{name:'Demo: simular final del encuentro'}).click();await expect(page.getByRole('heading',{name:'Un buen NOW.'})).toBeVisible();await page.getByRole('button',{name:'Me sentí a gusto'}).click();await expect(page.getByRole('status')).toContainText('feedback');
 await page.getByRole('button',{name:'Comunidades',exact:true}).click();const campus=page.locator('.community-card').filter({has:page.getByRole('heading',{name:'Universidad de Sevilla'})});await expect(campus).toContainText('64 personas');await expect(campus).toContainText('personas por conocer');await campus.getByRole('button',{name:'Ver encuentros de la comunidad'}).click();await expect(campus).toContainText('asistencias');
 await page.locator('.user-mini').click();await expect(page.getByRole('heading',{name:'Tu histórico de NOWs'})).toBeVisible();await expect(page.getByRole('heading',{name:'Personas con las que coincidiste'})).toBeVisible();await page.getByRole('button',{name:'Chats',exact:true}).click();await expect(page.getByRole('heading',{name:'Tus chats.'})).toBeVisible();
});
test('alta OTP → verificar comunidad → intención → grupo confirmado',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.getByLabel('Email',{exact:true}).fill(`e2e-${Date.now()}@example.test`);await page.getByLabel('Tu nombre',{exact:true}).fill('Eva');await page.getByLabel('Fecha de nacimiento').fill('2001-04-12');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Recibir código'}).click();
 const code=await page.getByText('Código local de prueba:').textContent();await page.getByLabel('Código',{exact:true}).fill(code!.match(/\d{6}/)![0]);await page.getByRole('button',{name:'Entrar en NOW'}).click();await expect(page.getByRole('heading',{name:'¿Qué te apetece, Eva?'})).toBeVisible();
 await page.getByRole('button',{name:'Comunidades',exact:true}).click();const campus=page.locator('.community-card').filter({has:page.getByRole('heading',{name:'Universidad de Sevilla'})});await campus.getByLabel('Código de comunidad').fill('CAMPUS-NOW');await campus.getByRole('button',{name:'Unirme'}).click();await expect(campus.getByText('Comunidad verificada')).toBeVisible();
 await page.getByRole('button',{name:'Mi NOW',exact:true}).click();await page.getByRole('button',{name:'☕ Café'}).click();await page.getByRole('button',{name:'Usar campus de demostración'}).click();await page.getByRole('button',{name:/Café tranquilo/}).click();await page.getByRole('button',{name:/2 horas/}).click();await page.getByRole('button',{name:/Mi comunidad/}).click();await page.getByRole('button',{name:'VOY',exact:true}).click();await expect(page.getByRole('heading',{name:'Nos vemos fuera.'})).toBeVisible();
 await page.getByRole('button',{name:'Seguridad',exact:true}).click();await page.getByRole('button',{name:'No me siento a gusto. Salir.'}).click();await expect(page.getByRole('status')).toContainText('sin penalización');
 await page.getByRole('button',{name:'Ajustes y privacidad'}).click();await page.getByRole('button',{name:'Eliminar mi cuenta',exact:true}).click();await page.getByLabel('Escribe ELIMINAR para confirmar').fill('ELIMINAR');await page.getByRole('button',{name:'Eliminar mi cuenta definitivamente'}).click();await expect(page.getByRole('heading',{name:/Estoy libre/})).toBeVisible();
});
test('vista móvil responde sin desbordar y permite cancelación',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.screenshot({path:'test-results/now-landing-mobile.png',fullPage:true});await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.getByRole('button',{name:'Lucía',exact:true}).click();await page.getByRole('button',{name:'📚 Estudiar'}).click();await page.getByRole('button',{name:'Usar campus de demostración'}).click();await page.getByRole('button',{name:/Ir a la biblioteca/}).click();await page.getByRole('button',{name:/1 hora/}).click();await page.getByRole('button',{name:/Mi comunidad/}).click();await expect(page.getByRole('button',{name:'VOY',exact:true})).toBeVisible();await page.screenshot({path:'test-results/now-proposal-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.getByRole('button',{name:'Ahora paso'}).click();await expect(page.getByRole('heading',{name:'Todo empieza con un «me apetece…»'})).toBeVisible();
});
test('admin: métricas y configuración auditada',async({page})=>{
 await page.goto('http://localhost:3102');await page.getByRole('textbox',{name:'Usuario'}).fill('admin');await page.getByLabel('Contraseña').fill(process.env.DEMO_ADMIN_PASSWORD||'');await page.getByRole('button',{name:'Entrar al panel'}).click();await expect(page.getByRole('heading',{name:'Resumen',exact:true})).toBeVisible();await page.getByRole('button',{name:'Funciones',exact:true}).click();const row=page.getByRole('row').filter({hasText:'surprise_mode'});await row.getByRole('button',{name:'Desactivar'}).click();await expect(row.getByRole('button',{name:'Activar'})).toBeVisible();await row.getByRole('button',{name:'Activar'}).click();await page.getByRole('button',{name:'Auditoría',exact:true}).click();await expect(page.getByRole('cell',{name:'flag.updated'}).first()).toBeVisible();
});
