import { config } from '../../config/src/index';
import type { Activity,MatchState,Visibility } from '../../types/src/index';
export type Geo={lat:number;lon:number};
export type Candidate={id:string;userId:string;activity:string;subtype?:string|null;start:number;end:number;expires:number;radius:number;visibility:Visibility;communityId?:string|null;location:Geo;status:string;accountStatus:string;over18:boolean;trust:string;communities:string[];reliability:number;budget:number;accessible:boolean;country:string};
export type Graph={friends:Set<string>;blocks:Set<string>;riskPairs:Set<string>;metBefore:Set<string>};
export const pair=(a:string,b:string)=>[a,b].sort().join(':');
export function distance(a:Geo,b:Geo){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlon=(b.lon-a.lon)*r;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlon/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export function quantize(p:Geo):Geo{return {lat:Math.round(p.lat/config.geoStep)*config.geoStep,lon:Math.round(p.lon/config.geoStep)*config.geoStep};}
export function distanceBand(m:number){return m<1000?'~'+Math.max(500,Math.round(m/500)*500)+' m':'~'+(Math.round(m/500)/2).toLocaleString('es-ES')+' km';}
export function isAdult(birth:string,now=new Date()){const b=new Date(birth+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(birth)||Number.isNaN(+b)||b.toISOString().slice(0,10)!==birth)return false;const cutoff=new Date(Date.UTC(now.getUTCFullYear()-18,now.getUTCMonth(),now.getUTCDate()));return b<=cutoff&&now.getUTCFullYear()-b.getUTCFullYear()<120;}
export function socialLevel(a:Candidate,b:Candidate,g:Graph){if(g.friends.has(pair(a.userId,b.userId)))return 1;const adjacent=(id:string)=>[...g.friends].flatMap(p=>{const [x,y]=p.split(':');return x===id?[y]:y===id?[x]:[];});const af=adjacent(a.userId);if(adjacent(b.userId).some(id=>af.includes(id)&&!g.blocks.has(pair(id,a.userId))&&!g.blocks.has(pair(id,b.userId))))return .8;if(a.communities.some(x=>b.communities.includes(x)))return .6;return .25;}
function visibilityAllows(a:Candidate,b:Candidate,g:Graph){const level=socialLevel(a,b,g);if(a.visibility==='friends')return level===1;if(a.visibility==='fof')return level>=.8;if(a.visibility==='community')return !!a.communityId&&a.communities.includes(a.communityId)&&b.communities.includes(a.communityId);return a.trust!=='basic'&&b.trust!=='basic';}
export function activityFit(a:string,b:string,activities:Activity[]){if(a===b)return 1;const x=activities.find(v=>v.id===a),y=activities.find(v=>v.id===b);return x?.compatible.includes(b)&&y?.compatible.includes(a)?0.75:0;}
export function eligible(a:Candidate,b:Candidate,g:Graph,activities:Activity[],now:number){return a.userId!==b.userId&&[a,b].every(x=>x.status==='SEARCHING'&&x.accountStatus==='active'&&x.over18&&x.expires>now)&&a.country===b.country&&!g.blocks.has(pair(a.userId,b.userId))&&!g.riskPairs.has(pair(a.userId,b.userId))&&!!activityFit(a.activity,b.activity,activities)&&!(a.activity===b.activity&&a.subtype&&b.subtype&&a.subtype!==b.subtype)&&Math.min(a.end,b.end)-Math.max(a.start,b.start,now+config.travelMinutes*60000)>=config.minOverlapMinutes*60000&&distance(a.location,b.location)<=Math.min(a.radius,b.radius)&&visibilityAllows(a,b,g)&&visibilityAllows(b,a,g);}
export function score(a:Candidate,b:Candidate,g:Graph,activities:Activity[]){const components={activity:activityFit(a.activity,b.activity,activities),time:Math.min(1,(Math.min(a.end,b.end)-Math.max(a.start,b.start))/7200000),distance:Math.max(0,1-distance(a.location,b.location)/Math.min(a.radius,b.radius)),reliability:(a.reliability+b.reliability)/200,social:socialLevel(a,b,g),practical:1-Math.abs(a.budget-b.budget)/3,novelty:g.metBefore.has(pair(a.userId,b.userId))?.3:1};const total=(Object.keys(components) as (keyof typeof components)[]).reduce((s,k)=>s+components[k]*config.weights[k],0);return {total,components};}
/** Greedy max-min clique. Every pair must satisfy every hard constraint. */
export function formGroup(anchor:Candidate,pool:Candidate[],g:Graph,activities:Activity[],now:number,size:number=config.preferredGroup){const group=[anchor];let candidates=pool.filter(c=>eligible(anchor,c,g,activities,now));while(group.length<Math.min(config.maxGroup,size)&&candidates.length){candidates.sort((a,b)=>Math.min(...group.map(x=>score(x,b,g,activities).total))-Math.min(...group.map(x=>score(x,a,g,activities).total))||a.id.localeCompare(b.id));const next=candidates.shift()!;if(group.every(x=>eligible(x,next,g,activities,now))&&Math.min(...group.map(x=>x.end),next.end)-Math.max(...group.map(x=>x.start),next.start,now+config.travelMinutes*60000)>=config.minOverlapMinutes*60000)group.push(next);candidates=candidates.filter(c=>group.every(x=>eligible(x,c,g,activities,now)));}return group.length>=config.minGroup?group:[];}
export type Venue={id:string;name:string;location:Geo;activities:string[];public:boolean;safe:boolean;accessible:boolean;capacity:number;budget:number;rating:number;openHour:number;closeHour:number;timezone:string};
function hourAt(ms:number,tz:string){return Number(new Intl.DateTimeFormat('en',{timeZone:tz,hour:'numeric',hourCycle:'h23'}).format(ms));}
export function selectVenues(group:Candidate[],venues:Venue[],start:number,end:number){return venues.filter(v=>v.public&&v.safe&&v.capacity>=group.length&&group.every(c=>v.activities.includes(c.activity)||c.activity==='surprise')&&group.every(c=>(!c.accessible||v.accessible)&&v.budget<=c.budget&&distance(c.location,v.location)<=c.radius)).filter(v=>{const a=hourAt(start,v.timezone),b=hourAt(end,v.timezone);return v.openHour===v.closeHour||(v.openHour<v.closeHour?a>=v.openHour&&b<v.closeHour:a>=v.openHour||b<v.closeHour);}).map(v=>{const ds=group.map(c=>distance(c.location,v.location));return {venue:v,score:v.rating*100-Math.max(...ds)-.4*(Math.max(...ds)-Math.min(...ds))};}).sort((a,b)=>b.score-a.score||a.venue.id.localeCompare(b.venue.id)).slice(0,3).map(x=>x.venue);}
export function nextProposalState(state:MatchState,responses:string[],expires:number,now:number):MatchState{if(!['PROPOSAL_PENDING','PARTIALLY_ACCEPTED'].includes(state))return state;if(now>=expires)return 'EXPIRED';if(responses.includes('passed'))return 'CANCELLED';if(responses.length>=config.minGroup&&responses.every(x=>x==='accepted'))return 'CONFIRMED';return responses.includes('accepted')?'PARTIALLY_ACCEPTED':'PROPOSAL_PENDING';}
/** Bayesian prior protects newcomers; safety exits never count as failures. */
export function reliability(attended:number,accepted:number,lateCancels=0){return Math.round(100*(Math.max(0,attended)+8)/(Math.max(accepted,attended)+10+Math.max(0,lateCancels)*.5));}
export function radarBand(count:number){return count<config.radarK?'Actividad por descubrir':count<6?'3–5 personas compatibles':count<10?'6–9 personas compatibles':'10+ personas compatibles';}
export function textAllowed(text:string){return !/(https?:\/\/|www\.|\b\d[\d\s+()-]{7,}\d\b|\S+@\S+\.\S+|\b(?:sexo|porno|matarte|violación|nudes|bizum)\b)/iu.test(text);}
