import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,View,Text,Pressable,TextInput,StyleSheet} from 'react-native';
import {NowClient} from '../../packages/api-client/src/index';
import {useForegroundPolling} from './useForegroundPolling';
import type {CommunityEventView,CommunityView,HistoryView,MessageView,PersonSummary} from '../../packages/types/src/index';
type Props={api:NowClient};
const date=(value:string)=>new Date(value).toLocaleDateString('es-ES');
const messageOf=(error:unknown,fallback:string)=>error instanceof Error?error.message:fallback;

export function MobileCommunityEvents({api,community}:{api:NowClient;community:CommunityView}){
 const [events,setEvents]=useState<CommunityEventView[]|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const loadingRef=useRef(false);
 const load=useCallback(async()=>{if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setError('');try{setEvents(await api.request<CommunityEventView[]>('/v1/communities/'+community.id+'/events'));}catch(e){setError(messageOf(e,'No pudimos cargar los encuentros. Comprueba tu conexión e inténtalo de nuevo.'));}finally{loadingRef.current=false;setLoading(false);}},[api,community.id]);
 return <View><Pressable accessibilityRole="button" accessibilityState={{disabled:loading}} disabled={loading} onPress={()=>{if(events){setEvents(null);setError('');return;}void load();}}><Text style={styles.link}>{events?'Ocultar encuentros':'Ver encuentros de la comunidad →'}</Text></Pressable>{loading&&<ActivityIndicator color="#577239"/>}{error&&<View><Text style={styles.error}>{error}</Text><Pressable accessibilityRole="button" disabled={loading} onPress={()=>void load()}><Text style={styles.link}>Reintentar →</Text></Pressable></View>}{events?.length===0&&<Text style={styles.sub}>Aún no hay encuentros en esta comunidad.</Text>}{events?.map(e=><View style={styles.item} key={e.id}><Text style={styles.title}>{e.activity.emoji} {e.activity.label}</Text><Text style={styles.sub}>{date(e.scheduledAt)} · {e.attendeeCount} asistencias</Text>{e.attendedByMe&&e.attendees?e.attendees.map(p=><Text style={styles.sub} key={p.id}>✓ {p.displayName}</Text>):<Text style={styles.sub}>Los asistentes solo se muestran si participaste.</Text>}</View>)}</View>;
}

export function MobileHistory({api}:Props){
 const [history,setHistory]=useState<HistoryView[]>([]),[people,setPeople]=useState<PersonSummary[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);const loadingRef=useRef(false);
 const load=useCallback(async()=>{if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setError('');try{const [h,p]=await Promise.all([api.request<HistoryView[]>('/v1/me/history'),api.request<PersonSummary[]>('/v1/me/people')]);setHistory(h);setPeople(p);}catch(e){setError(messageOf(e,'No pudimos cargar tu historial. Comprueba tu conexión e inténtalo de nuevo.'));}finally{loadingRef.current=false;setLoading(false);}},[api]);
 useEffect(()=>{void load();},[load]);
 return <View style={styles.card}><Text style={styles.heading}>Mi historia.</Text>{loading&&<View style={styles.loading}><ActivityIndicator color="#577239"/><Text style={styles.sub}>Cargando tu historial…</Text></View>}{error&&<View><Text style={styles.error}>{error}</Text><Pressable accessibilityRole="button" disabled={loading} onPress={()=>void load()}><Text style={styles.link}>Reintentar →</Text></Pressable></View>}<Text style={styles.title}>Personas con las que coincidiste</Text>{!loading&&!error&&people.length===0?<Text style={styles.sub}>Aparecerán después de asistir a un NOW juntos.</Text>:people.map(p=><Text style={styles.sub} key={p.id}>✓ {p.displayName}</Text>)}<Text style={[styles.title,{marginTop:18}]}>Histórico de NOWs</Text>{!loading&&!error&&history.length===0?<Text style={styles.sub}>Todavía no tienes NOWs en tu historial.</Text>:history.map(h=><View style={styles.item} key={h.id}><Text style={styles.title}>{h.activity.emoji} {h.activity.label}</Text><Text style={styles.sub}>{date(h.scheduledAt)} · {h.community?.name||'Tu círculo'}</Text><Text style={styles.sub}>{h.participants.map(p=>p.displayName).join(', ')}</Text></View>)}</View>;
}

export function MobileChats({api}:Props){
 const [items,setItems]=useState<HistoryView[]>([]),[selected,setSelected]=useState<HistoryView|null>(null),[messages,setMessages]=useState<MessageView[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState(''),[pollingError,setPollingError]=useState(''),[listLoading,setListLoading]=useState(true),[listError,setListError]=useState(''),[messagesLoading,setMessagesLoading]=useState(false),[sending,setSending]=useState(false);const listLoadingRef=useRef(false),messagePromise=useRef<Promise<void>|null>(null),loadedChatId=useRef<string|null>(null),selectedChatId=useRef<string|null>(null);
 const loadChats=useCallback(async()=>{if(listLoadingRef.current)return;listLoadingRef.current=true;setListLoading(true);setListError('');try{setItems(await api.request<HistoryView[]>('/v1/me/conversations'));}catch(e){setListError(messageOf(e,'No pudimos cargar tus chats. Comprueba tu conexión e inténtalo de nuevo.'));}finally{listLoadingRef.current=false;setListLoading(false);}},[api]);
 useEffect(()=>{void loadChats();},[loadChats]);
 const selectChat=(chat:HistoryView)=>{selectedChatId.current=chat.id;loadedChatId.current=null;messagePromise.current=null;setMessages([]);setPollingError('');setError('');setDraft('');setSelected(chat);};
 const loadMessages=useCallback(async()=>{const chatId=selected?.id;if(!chatId||!selected?.chatOpen)return;if(messagePromise.current)return messagePromise.current;const firstLoad=loadedChatId.current!==chatId;if(firstLoad)setMessagesLoading(true);const request=(async()=>{try{const result=await api.request<MessageView[]>('/v1/matches/'+chatId+'/messages');if(selectedChatId.current===chatId){setMessages(result);setPollingError('');loadedChatId.current=chatId;}}finally{if(firstLoad)setMessagesLoading(false);}})();messagePromise.current=request;try{await request;}finally{if(messagePromise.current===request)messagePromise.current=null;}},[api,selected?.id,selected?.chatOpen]);
 const pollError=useCallback((e:unknown)=>setPollingError(messageOf(e,'No se pudo actualizar el chat. Comprueba la conexión e inténtalo de nuevo.')) ,[]);
 useForegroundPolling(!!selected?.chatOpen,5000,loadMessages,pollError,'messages:'+selected?.id);
 const send=async()=>{if(!selected||!draft.trim()||sending)return;setSending(true);setError('');try{await api.mutation('/v1/matches/'+selected.id+'/messages',{body:draft});setDraft('');await loadMessages();}catch(e){setError(messageOf(e,'No se pudo enviar. Comprueba tu conexión e inténtalo de nuevo.'));}finally{setSending(false);}};
 return <View style={styles.card}><Text style={styles.heading}>Tus chats.</Text><Text style={styles.sub}>Cada chat nace de un NOW compartido y dura 30 días después.</Text>{listLoading&&<View style={styles.loading}><ActivityIndicator color="#577239"/><Text style={styles.sub}>Cargando chats…</Text></View>}{listError&&<View><Text style={styles.error}>{listError}</Text><Pressable accessibilityRole="button" disabled={listLoading} onPress={()=>void loadChats()}><Text style={styles.link}>Reintentar →</Text></Pressable></View>}{!listLoading&&!listError&&items.length===0&&<Text style={styles.sub}>Aquí aparecerán los chats de tus NOWs.</Text>}{!listError&&items.map(h=><Pressable key={h.id} accessibilityRole="button" accessibilityState={{selected:selected?.id===h.id}} onPress={()=>selectChat(h)} style={[styles.item,selected?.id===h.id&&styles.selected]}><Text style={styles.title}>{h.activity.emoji} {h.activity.label}</Text><Text style={styles.sub}>{date(h.scheduledAt)} · {h.lastMessage||'Abrir conversación'}</Text></Pressable>)}{selected&&<View style={styles.item}><Text style={styles.title}>{selected.activity.label}</Text>{messagesLoading&&<View style={styles.loading}><ActivityIndicator color="#577239"/><Text style={styles.sub}>Cargando mensajes…</Text></View>}{pollingError&&<View><Text style={styles.error}>{pollingError}</Text><Pressable accessibilityRole="button" disabled={messagesLoading} onPress={()=>void loadMessages().catch(pollError)}><Text style={styles.link}>Reintentar →</Text></Pressable></View>}{!messagesLoading&&!pollingError&&messages.length===0&&<Text style={styles.sub}>Aún no hay mensajes en esta conversación.</Text>}{messages.map(m=><View style={styles.item} key={m.id}><Text style={styles.title}>{m.displayName}</Text><Text>{m.body}</Text></View>)}{selected.chatOpen?<><TextInput accessibilityLabel="Mensaje al grupo" value={draft} onChangeText={setDraft} placeholder="Escribe al grupo" style={styles.input}/><Pressable accessibilityRole="button" disabled={!draft.trim()||sending} onPress={()=>void send()}><Text style={styles.link}>{sending?'Enviando…':'Enviar →'}</Text></Pressable></>:<Text style={styles.sub}>Este chat ya ha terminado.</Text>}{error&&<Text style={styles.error}>{error}</Text>}</View>}</View>;
}
const styles=StyleSheet.create({card:{backgroundColor:'#fff',padding:23,borderWidth:1,borderColor:'#dce3d6',borderRadius:23,marginBottom:22},item:{paddingVertical:14,borderBottomWidth:1,borderColor:'#e1e6d9'},selected:{backgroundColor:'#f0f5e9'},heading:{fontSize:28,fontWeight:'600',color:'#1c382a',marginBottom:15},title:{fontSize:16,fontWeight:'600',color:'#1c382a'},sub:{fontSize:12,color:'#718062',lineHeight:19,marginTop:5},link:{fontSize:13,color:'#58703e',fontWeight:'700',paddingVertical:14},error:{fontSize:12,color:'#a3442e',marginTop:8},loading:{flexDirection:'row',alignItems:'center',gap:8,paddingVertical:10},input:{borderWidth:1,borderColor:'#d9e0cf',borderRadius:10,minHeight:48,padding:13,marginTop:14,color:'#2d4932'}});
