import React,{useEffect,useState} from 'react';
import {View,Text,Pressable,TextInput,StyleSheet} from 'react-native';
import {NowClient} from '../../packages/api-client/src/index';
import type {CommunityEventView,CommunityView,HistoryView,MessageView,PersonSummary} from '../../packages/types/src/index';
type Props={api:NowClient};
const date=(value:string)=>new Date(value).toLocaleDateString('es-ES');

export function MobileCommunityEvents({api,community}:{api:NowClient;community:CommunityView}){
 const [events,setEvents]=useState<CommunityEventView[]|null>(null),[error,setError]=useState('');
 return <View><Pressable accessibilityRole="button" onPress={()=>{if(events){setEvents(null);return;}void api.request<CommunityEventView[]>('/v1/communities/'+community.id+'/events').then(setEvents).catch(e=>setError(e instanceof Error?e.message:'No pudimos cargar los encuentros.'));}}><Text style={styles.link}>{events?'Ocultar encuentros':'Ver encuentros de la comunidad →'}</Text></Pressable>{error&&<Text style={styles.error}>{error}</Text>}{events?.map(e=><View style={styles.item} key={e.id}><Text style={styles.title}>{e.activity.emoji} {e.activity.label}</Text><Text style={styles.sub}>{date(e.scheduledAt)} · {e.attendeeCount} asistencias</Text>{e.attendedByMe&&e.attendees?e.attendees.map(p=><Text style={styles.sub} key={p.id}>✓ {p.displayName}</Text>):<Text style={styles.sub}>Los asistentes solo se muestran si participaste.</Text>}</View>)}</View>;
}

export function MobileHistory({api}:Props){
 const [history,setHistory]=useState<HistoryView[]>([]),[people,setPeople]=useState<PersonSummary[]>([]),[error,setError]=useState('');
 useEffect(()=>{void Promise.all([api.request<HistoryView[]>('/v1/me/history'),api.request<PersonSummary[]>('/v1/me/people')]).then(([h,p])=>{setHistory(h);setPeople(p);}).catch(e=>setError(e instanceof Error?e.message:'No pudimos cargar tu historial.'));},[api]);
 return <View style={styles.card}><Text style={styles.heading}>Mi historia.</Text><Text style={styles.title}>Personas con las que coincidiste</Text>{people.length?people.map(p=><Text style={styles.sub} key={p.id}>✓ {p.displayName}</Text>):<Text style={styles.sub}>Aparecerán después de asistir a un NOW juntos.</Text>}<Text style={[styles.title,{marginTop:18}]}>Histórico de NOWs</Text>{history.map(h=><View style={styles.item} key={h.id}><Text style={styles.title}>{h.activity.emoji} {h.activity.label}</Text><Text style={styles.sub}>{date(h.scheduledAt)} · {h.community?.name||'Tu círculo'}</Text><Text style={styles.sub}>{h.participants.map(p=>p.displayName).join(', ')}</Text></View>)}{error&&<Text style={styles.error}>{error}</Text>}</View>;
}

export function MobileChats({api}:Props){
 const [items,setItems]=useState<HistoryView[]>([]),[selected,setSelected]=useState<HistoryView|null>(null),[messages,setMessages]=useState<MessageView[]>([]),[draft,setDraft]=useState(''),[error,setError]=useState('');
 useEffect(()=>{void api.request<HistoryView[]>('/v1/me/conversations').then(setItems).catch(e=>setError(e instanceof Error?e.message:'No pudimos cargar tus chats.'));},[api]);
 useEffect(()=>{if(!selected?.chatOpen)return;const load=()=>api.request<MessageView[]>('/v1/matches/'+selected.id+'/messages').then(setMessages).catch(()=>{});void load();const timer=setInterval(()=>void load(),5000);return()=>clearInterval(timer);},[api,selected?.id,selected?.chatOpen]);
 const send=async()=>{if(!selected||!draft.trim())return;try{await api.mutation('/v1/matches/'+selected.id+'/messages',{body:draft});setDraft('');setMessages(await api.request('/v1/matches/'+selected.id+'/messages'));}catch(e){setError(e instanceof Error?e.message:'No se pudo enviar.');}};
 return <View style={styles.card}><Text style={styles.heading}>Tus chats.</Text><Text style={styles.sub}>Cada chat nace de un NOW compartido y dura 30 días después.</Text>{items.length?items.map(h=><Pressable key={h.id} accessibilityRole="button" onPress={()=>setSelected(h)} style={styles.item}><Text style={styles.title}>{h.activity.emoji} {h.activity.label}</Text><Text style={styles.sub}>{date(h.scheduledAt)} · {h.lastMessage||'Abrir conversación'}</Text></Pressable>):<Text style={styles.sub}>Aquí aparecerán los chats de tus NOWs.</Text>}{selected&&<View style={styles.item}><Text style={styles.title}>{selected.activity.label}</Text>{messages.map(m=><View style={styles.item} key={m.id}><Text style={styles.title}>{m.displayName}</Text><Text>{m.body}</Text></View>)}{selected.chatOpen?<><TextInput accessibilityLabel="Mensaje al grupo" value={draft} onChangeText={setDraft} placeholder="Escribe al grupo" style={styles.input}/><Pressable accessibilityRole="button" disabled={!draft.trim()} onPress={()=>void send()}><Text style={styles.link}>Enviar →</Text></Pressable></>:<Text style={styles.sub}>Este chat ya ha terminado.</Text>}</View>}{error&&<Text style={styles.error}>{error}</Text>}</View>;
}
const styles=StyleSheet.create({card:{backgroundColor:'#fff',padding:23,borderWidth:1,borderColor:'#dce3d6',borderRadius:23,marginBottom:22},item:{paddingVertical:14,borderBottomWidth:1,borderColor:'#e1e6d9'},heading:{fontSize:28,fontWeight:'600',color:'#1c382a',marginBottom:15},title:{fontSize:16,fontWeight:'600',color:'#1c382a'},sub:{fontSize:12,color:'#718062',lineHeight:19,marginTop:5},link:{fontSize:13,color:'#58703e',fontWeight:'700',paddingVertical:14},error:{fontSize:12,color:'#a3442e',marginTop:8},input:{borderWidth:1,borderColor:'#d9e0cf',borderRadius:10,minHeight:48,padding:13,marginTop:14,color:'#2d4932'}});
