import { Database } from './client';
import { migrate } from './migrate';
import { id,hash } from '../apps/api/src/crypto';
import { env } from '../apps/api/src/env';
export const defaultPreferences={notifications:true,liquidity:false,quietStart:23,quietEnd:8,timezone:'Europe/Madrid',radius:2000,analytics:false,interests:[],interestSubtypes:{},interestAlerts:false};
export const activitySeed=[
 ['coffee','Café','☕','social',['coffee','social','food','surprise']],['social','Tomar algo','🍺','social',['social','coffee','food','surprise']],['food','Comer','🍕','food',['food','coffee','social','surprise']],['sport','Deporte','⚽','sport',['sport','move','surprise']],['move','Moverme','🏃','sport',['move','sport','walk','surprise']],['study','Estudiar','📚','study',['study','surprise']],['game','Jugar','🎮','game',['game','surprise']],['music','Música','🎵','music',['music','surprise']],['walk','Pasear','🚶','outdoor',['walk','move','surprise']],['surprise','Sorpréndeme','🎲','surprise',['coffee','social','food','sport','move','study','game','music','walk','surprise']]
] as const;
export const activityOptions:Record<string,[string,string,string][]>={
 coffee:[['tranquilo','Café tranquilo','☕'],['especialidad','Café de especialidad','🫘'],['para_llevar','Para llevar y pasear','🥤']],
 social:[['cerveza','Una cerveza','🍺'],['vino','Una copa de vino','🍷'],['sin_alcohol','Algo sin alcohol','🧃'],['terraza','Sentarnos en una terraza','🌤️']],
 food:[['tapas','Tapas','🥘'],['pizza','Pizza','🍕'],['asiatica','Comida asiática','🍜'],['vegana','Vegana o vegetariana','🥗'],['postre','Un postre','🍰']],
 sport:[['futbol','Fútbol','⚽'],['padel','Pádel','🎾'],['running','Running','🏃'],['gimnasio','Entrenar juntos','🏋️'],['otro','Otro deporte','🏅']],
 move:[['running','Salir a correr','🏃'],['bici','Bici','🚲'],['patines','Patines','🛼'],['entrenar','Mover el cuerpo','💪']],
 study:[['biblioteca','Ir a la biblioteca','📚'],['coworking','Coworking','💻'],['idiomas','Practicar idiomas','🗣️'],['proyecto','Avanzar un proyecto','✏️']],
 game:[['mesa','Juegos de mesa','🎲'],['cartas','Cartas','🃏'],['videojuegos','Videojuegos','🎮'],['ajedrez','Ajedrez','♟️']],
 music:[['concierto','Ir a un concierto','🎤'],['jam','Tocar juntos','🎸'],['escuchar','Compartir música','🎧'],['bailar','Bailar','💃']],
 walk:[['parque','Por un parque','🌳'],['ciudad','Descubrir la ciudad','🏙️'],['naturaleza','Naturaleza','🥾'],['fotografia','Paseo con fotos','📷']],
 surprise:[['sorpresa','Elige por mí','✨']]
};
export async function seed(db:Database,demo=env.demo){await db.tx(async q=>{for(const [a,label,emoji,family,compatible] of activitySeed){await q.exec('INSERT INTO activities(id,label,emoji,family,compatible) VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT DO NOTHING',[a,label,emoji,family,JSON.stringify(compatible)]);await q.exec('UPDATE activities SET options=$1::jsonb WHERE id=$2',[JSON.stringify(activityOptions[a].map(([id,label,emoji])=>({id,label,emoji}))),a]);}for(const [key,enabled,description] of [['open_strangers_matching',false,'Abierto sólo con proof-of-age y teléfono verificados'],['venue_promotions',false,'Promociones desactivadas'],['chat_enabled',true,'Chat de grupo efímero'],['surprise_mode',true,'Actividad sorpresa'],['friend_of_friend',true,'Amigos de amigos'],['community_matching',true,'Comunidades verificadas']])await q.exec('INSERT INTO feature_flags VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[key,enabled,description]);if(!demo)return;if(await q.one('SELECT id FROM users LIMIT 1'))return;
 const now=Date.now();const campus=id(),residence=id(),erasmus=id();
 for(const [cid,name,kind,description,code] of [[campus,'Universidad de Sevilla','university','Reina Mercedes. Un rato libre, muchas posibilidades.','CAMPUS-NOW'],[residence,'Residencia del Sur','residence','Tu comunidad, a un paseo.','CASA-NOW'],[erasmus,'Erasmus Sevilla','international','La ciudad se descubre mejor en compañía.','ERASMUS-NOW']])await q.exec('INSERT INTO communities(id,name,kind,city,description,method,code_hash) VALUES($1,$2,$3,$4,$5,$6,$7)',[cid,name,kind,'Sevilla',description,'code',hash(code)]);
 const names=['José','Ana','Carlos','Lucía','Pablo','Marta','Álex','Elena','Diego','Sara','Hugo','Carmen','Nico','Paula','Leo','Alba'];const userIds:string[]=[];
 for(let i=0;i<64;i++){const uid=id();userIds.push(uid);const base=['jose','ana','carlos','lucia'][i]||'campus'+(i+1);await q.exec('INSERT INTO users(id,username,display_name,over18,age_status,trust,is_demo,role,created_at,updated_at) VALUES($1,$2,$3,true,$4,$5,true,$6,$7,$7)',[uid,base,names[i%names.length]+(i>=16?' '+String(Math.floor(i/16)+1):''),'demo_verified','community',i===63?'admin':'user',now-i*86400000]);if(i>=4&&i!==63)await q.exec('UPDATE users SET is_demo_actor=true WHERE id=$1',[uid]);await q.exec('INSERT INTO identity.contacts(user_id,email,birth_date) VALUES($1,$2,$3)',[uid,i===63?'admin@now.demo':base+'@now.demo','2002-05-15']);await q.exec('INSERT INTO preferences VALUES($1,$2::jsonb)',[uid,JSON.stringify(defaultPreferences)]);await q.exec('INSERT INTO reliability_profiles VALUES($1,$2,$3,0)',[uid,10+i%9,9+i%9]);await q.exec('INSERT INTO memberships VALUES($1,$2,true,$3)',[uid,campus,now]);if(i%3===0)await q.exec('INSERT INTO memberships VALUES($1,$2,true,$3)',[uid,residence,now]);if(i%4===0)await q.exec('INSERT INTO memberships VALUES($1,$2,true,$3)',[uid,erasmus,now]);await q.exec('INSERT INTO consents VALUES($1,$2,$3,true,$4,$5)',[id(),uid,'terms','2026-09',now]);}
 for(let i=0;i<64;i++)for(const offset of [1,2]){const a=userIds[i],b=userIds[(i+offset)%64];await q.exec('INSERT INTO friendships VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[...[a,b].sort(),'accepted',now]);}
 const pois=[['Café del Campus','Café','Av. Reina Mercedes · punto de encuentro ficticio',37.359,-5.985,['coffee','social','food','study']],['La Terraza NOW','Terraza','Zona Reina Mercedes · punto de encuentro ficticio',37.358,-5.987,['social','coffee','food','music']],['Jardín de la Ciencia','Parque','Campus Reina Mercedes · punto de encuentro ficticio',37.361,-5.984,['walk','move','sport']],['Biblioteca del Sur','Biblioteca','Campus Reina Mercedes · punto de encuentro ficticio',37.357,-5.986,['study']],['Pistas del Campus','Deporte','Campus Reina Mercedes · punto de encuentro ficticio',37.36,-5.988,['sport','move']],['La Mesa Compartida','Restaurante','Zona campus · punto de encuentro ficticio',37.356,-5.984,['food','social','coffee']],['Ludoteca NOW','Juegos','Campus Reina Mercedes · punto de encuentro ficticio',37.36,-5.983,['game','music']]];
 for(const [name,category,address,lat,lon,activities] of pois)await q.exec('INSERT INTO venues(id,name,category,address,lat,lon,activities,safe,is_demo,budget) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,true,true,0)',[id(),name,category,address,lat,lon,JSON.stringify(activities)]);
 // Demo history is explicit; no synthetic analytics are mixed with measured live metrics.
 for(let n=0;n<5;n++){const mid=id();const v=await q.one<{id:string}>('SELECT id FROM venues ORDER BY name LIMIT 1');await q.exec('INSERT INTO matches(id,activity,subtype,community_id,venue_id,state,scheduled_at,ends_at,expires_at,created_at,confirmed_at,is_demo) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$7,$7,true)',[mid,'coffee','tranquilo',campus,v!.id,'COMPLETED',now-(n+1)*86400000,now-(n+1)*86400000+3600000,now-(n+1)*86400000]);for(const uid of userIds.slice(n*4,n*4+4)){await q.exec('INSERT INTO match_members(match_id,user_id,response,checked_in) VALUES($1,$2,$3,true)',[mid,uid,'accepted']);await q.exec('INSERT INTO attendance_verifications(match_id,subject_id,state,required_yes,auto_verified,decided_at) VALUES($1,$2,\'verified\',0,true,$3) ON CONFLICT DO NOTHING',[mid,uid,now-(n+1)*86400000+3600000]);}}
 });console.log(JSON.stringify({event:'seed.ready',demo}));}
export async function seedLiquidity(db:Database){await db.tx(async q=>{const now=Date.now();const campus=await q.one<{id:string}>('SELECT id FROM communities WHERE name=$1',['Universidad de Sevilla']);if(!campus)return;const users=await q.all<{id:string;username:string}>('SELECT id,username FROM users WHERE is_demo_actor=true AND status=$1 AND role=$2 ORDER BY username',['active','user']);let index=0;for(const u of users){if(['jose','ana','carlos','lucia'].includes(u.username))continue;if(await q.one('SELECT id FROM intents WHERE user_id=$1 AND status IN (\'SEARCHING\',\'RESERVED\')',[u.id]))continue;if(await q.one('SELECT m.id FROM matches m JOIN match_members mm ON mm.match_id=m.id WHERE mm.user_id=$1 AND m.state=$2 AND mm.safety_exit=false',[u.id,'CONFIRMED']))continue;const a=activitySeed[index%9][0];const lat=37.36+(index%3-1)*.005,lon=-5.985+(index%2)*.005;await q.exec('INSERT INTO intents(id,user_id,activity,start_at,end_at,expires_at,radius,visibility,community_id,status,lat,lon,cell_x,cell_y,created_at) VALUES($1,$2,$3,$4,$5,$5,2000,$6,$7,$8,$9,$10,$11,$12,$4)',[id(),u.id,a,now,now+4*3600000,'community',campus.id,'SEARCHING',lat,lon,Math.round(lat/.005),Math.round(lon/.005)]);index++;}});}
if(process.argv[1]?.endsWith('seed.ts')){const db=await Database.open();await migrate(db);await seed(db);if(env.demo)await seedLiquidity(db);await db.close();}
