import { randomInt } from 'node:crypto';
import { z } from 'zod';
import { type Database,type Query } from '../../../db/client';
import { isAdult,textAllowed } from '../../../packages/domain/src/index';
import { ApiError } from '../../../packages/types/src/index';
import { config } from '../../../packages/config/src/index';
import { defaultPreferences } from '../../../db/seed';
import { id,token,hash,digestEqual } from './crypto';
import { audit,limited,profile } from './core';
import { env } from './env';
import { mail } from './providers';
import type { User,Session } from './models';
export const signupSchema=z.object({email:z.email().max(254).transform(s=>s.toLowerCase()),displayName:z.string().trim().min(2).max(40).optional(),birthDate:z.string().optional(),country:z.enum(['ES','PT','FR','DE','IT','IE','NL','BE','AT']).default('ES'),terms:z.boolean().optional()});
export class AuthService {
 constructor(public db:Database){}
 async claimOidcNonce(q:Query,challenge:string,provider:'google'|'apple',nonce:string,binding:string){const c=await q.one<{code_hash:string;binding_hash:string}>('UPDATE auth_challenges SET used=true WHERE id=$1 AND email=$2 AND used=false AND expires_at>$3 RETURNING code_hash,binding_hash',[challenge,'oidc:'+provider,Date.now()]);if(!c||!digestEqual(c.code_hash,hash(nonce))||!digestEqual(c.binding_hash,hash(binding)))throw new ApiError('NONCE_INVALID','Vuelve a iniciar sesión.',401);}
 async request(input:z.infer<typeof signupSchema>,ip:string){if(input.birthDate&&!isAdult(input.birthDate))throw new ApiError('AGE_RESTRICTED','NOW es para mayores de 18 años.',403);if(input.displayName&&!textAllowed(input.displayName))throw new ApiError('NAME_INVALID','Usa tu nombre, sin datos de contacto.');await limited(this.db,'otp:'+input.email,4,600000);await limited(this.db,'signup-ip:'+ip,15,3600000);const code=String(randomInt(100000,1000000)),challenge=id(),binding=token();await this.db.tx(async q=>{await q.exec('INSERT INTO auth_challenges(id,email,code_hash,binding_hash,expires_at,data) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[challenge,input.email,hash(code),hash(binding),Date.now()+config.otpMinutes*60000,JSON.stringify(input)]);});await mail.sendCode(input.email,code);return {challenge,binding,message:'Si puedes acceder a esa dirección, recibirás un código.',...(env.demo?{demoCode:code}:{})};}
 async create(q:Query,email:string,data:{displayName?:string;birthDate?:string;country?:string;terms?:boolean}){let user=await q.one<User>('SELECT u.* FROM users u JOIN identity.contacts c ON c.user_id=u.id WHERE c.email=$1',[email]);if(user?.status==='deleted')throw new ApiError('ACCOUNT_UNAVAILABLE','Esta cuenta ya no está disponible.',403);if(!user){if(!data.displayName||!data.birthDate||!isAdult(data.birthDate)||!data.terms)throw new ApiError('ONBOARDING_REQUIRED','Introduce nombre, fecha de nacimiento y acepta las normas.',422);const uid=id(),now=Date.now();await q.exec('INSERT INTO users(id,username,display_name,country,over18,is_demo,created_at,updated_at) VALUES($1,$2,$3,$4,true,$5,$6,$6)',[uid,'now_'+uid.slice(0,8),data.displayName,data.country||'ES',env.demo,now]);await q.exec('INSERT INTO identity.contacts(user_id,email,birth_date) VALUES($1,$2,$3)',[uid,email,data.birthDate]);await q.exec('INSERT INTO preferences VALUES($1,$2::jsonb)',[uid,JSON.stringify(defaultPreferences)]);await q.exec('INSERT INTO reliability_profiles(user_id) VALUES($1)',[uid]);await q.exec('INSERT INTO consents VALUES($1,$2,$3,true,$4,$5)',[id(),uid,'terms','2026-09',now]);await audit(q,uid,'signup.completed');user=(await q.one<User>('SELECT * FROM users WHERE id=$1',[uid]))!;}return user;}
 async issue(q:Query,uid:string,device='Navegador',family:string=id()){const access=token(),refresh=token(),sid=id();await q.exec('INSERT INTO sessions VALUES($1,$2,$3,$4,$5,$6,$7,false,$8,$9)',[sid,uid,hash(access),hash(refresh),family,Date.now()+config.accessMinutes*60000,Date.now()+config.refreshDays*86400000,device.slice(0,100),Date.now()]);return {accessToken:access,refreshToken:refresh,sessionId:sid,user:await profile(q,uid)};}
 async verify(challenge:string,binding:string,code:string,device:string){const result=await this.db.tx(async q=>{const now=Date.now();const c=await q.one<{email:string;code_hash:string;binding_hash:string;attempts:number;expires_at:number;used:boolean;data:z.infer<typeof signupSchema>}>('UPDATE auth_challenges SET attempts=attempts+1 WHERE id=$1 AND used=false AND expires_at>$2 AND attempts<$3 RETURNING *',[challenge,now,5]);if(!c)return null;const bindingValid=digestEqual(hash(binding),c.binding_hash),codeValid=digestEqual(hash(code),c.code_hash);if(!bindingValid||!codeValid)return null;const claimed=await q.one<{id:string}>('UPDATE auth_challenges SET used=true WHERE id=$1 AND used=false AND expires_at>$2 AND attempts=$3 RETURNING id',[challenge,Date.now(),c.attempts]);if(!claimed)return null;const u=await this.create(q,c.email,c.data);await audit(q,u.id,'session.created');return this.issue(q,u.id,device);});if(!result)throw new ApiError('CODE_INVALID','El código no es válido o ha caducado.',401);return result;}
 async demo(email:string){if(!env.demo)throw new ApiError('NOT_FOUND','No disponible.',404);return this.db.tx(async q=>{const user=await q.one<User>('SELECT u.* FROM users u JOIN identity.contacts c ON c.user_id=u.id WHERE c.email=$1 AND u.is_demo=true AND u.status<>$2',[email,'deleted']);if(!user||user.role==='admin')throw new ApiError('DEMO_ACCOUNT','Elige una cuenta de demostración.',404);return this.issue(q,user.id,'Demo local');});}
 async demoAdmin(username:string,password:string){if(!env.demo||env.production)throw new ApiError('NOT_FOUND','No disponible.',404);if(!digestEqual(hash(username),hash(env.demoAdminUser))||!digestEqual(hash(password),hash(env.demoAdminPassword)))throw new ApiError('CREDENTIALS_INVALID','Usuario o contraseña incorrectos.',401);return this.db.tx(async q=>{const user=await q.one<User>("SELECT u.* FROM users u JOIN identity.contacts c ON c.user_id=u.id WHERE c.email=$1 AND u.is_demo=true AND u.status='active' AND u.role='admin'",['admin@now.demo']);if(!user)throw new ApiError('DEMO_ACCOUNT','La cuenta admin demo no está disponible.',404);return this.issue(q,user.id,'Admin demo local');});}
 async authenticate(access:string){return this.db.tx(async q=>{const s=await q.one<Session>('SELECT * FROM sessions WHERE access_hash=$1 AND revoked=false AND access_expires>$2',[hash(access),Date.now()]);if(!s)throw new ApiError('UNAUTHORIZED','Inicia sesión para continuar.',401);const u=await q.one<User>('SELECT * FROM users WHERE id=$1',[s.user_id]);if(!u||u.status==='deleted')throw new ApiError('UNAUTHORIZED','Inicia sesión para continuar.',401);return {user:u,session:s};});}
 async refresh(refresh:string){const result=await this.db.tx(async q=>{const s=await q.one<Session>('SELECT * FROM sessions WHERE refresh_hash=$1',[hash(refresh)]);if(!s||Number(s.expires_at)<=Date.now())return null;if(s.revoked){await q.exec('UPDATE sessions SET revoked=true WHERE family=$1',[s.family]);await audit(q,s.user_id,'session.refresh_reuse');return null;}await q.exec('UPDATE sessions SET revoked=true WHERE id=$1',[s.id]);const u=await q.one<User>('SELECT * FROM users WHERE id=$1',[s.user_id]);if(!u||u.status==='deleted')return null;return this.issue(q,s.user_id,s.device_name,s.family);});if(!result)throw new ApiError('UNAUTHORIZED','Vuelve a iniciar sesión.',401);return result;}
}
