import type { Query,Database } from '../../../db/client';
import type { Activity,UserView,Preferences } from '../../../packages/types/src/index';
import { ApiError } from '../../../packages/types/src/index';
import { config } from '../../../packages/config/src/index';
import { reliability } from '../../../packages/domain/src/index';
import type { User,PrefRow } from './models';
import { id,hash } from './crypto';
import { activityOptions,defaultPreferences } from '../../../db/seed';
export const ms=(n:unknown)=>Number(n);
export const iso=(n:unknown)=>new Date(Number(n)).toISOString();
export function requireValue<T>(v:T|null|undefined,code='NOT_FOUND',message='No encontramos lo que buscas.'):T{if(v===null||v===undefined)throw new ApiError(code,message,404);return v;}
export async function active(q:Query,uid:string){const u=requireValue(await q.one<User>('SELECT * FROM users WHERE id=$1',[uid]));if(u.status!=='active'||!u.over18)throw new ApiError('NOT_ELIGIBLE','Tu cuenta no puede usar el radar. Revisa tu estado en el perfil.',403);return u;}
export async function audit(q:Query,actor:string|null,action:string,subject:string|null=null,metadata:Record<string,unknown>={}){await q.exec('INSERT INTO audit_events VALUES($1,$2,$3,$4,$5::jsonb,$6)',[id(),actor,action,subject,JSON.stringify(metadata),Date.now()]);}
export async function metric(q:Query,name:string,activity:string|null=null,community:string|null=null,value=1){await q.exec('INSERT INTO analytics_events(id,name,activity,community_id,city,value,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[id(),name,activity,community,'Sevilla',value,Date.now()]);}
export async function notify(q:Query,uid:string,kind:string,title:string,body:string,ttl=86400000){const pref=(await q.one<PrefRow>('SELECT * FROM preferences WHERE user_id=$1',[uid]))?.data||defaultPreferences;if(!pref.notifications&&kind!=='safety')return;if(kind==='liquidity'&&!pref.liquidity)return;const n=await q.one<{count:string}>('SELECT count(*) FROM notifications WHERE user_id=$1 AND created_at>$2',[uid,Date.now()-86400000]);if(Number(n?.count)>=config.dailyPushCap&&kind!=='safety'&&kind!=='confirmation')return;await q.exec('INSERT INTO notifications(id,user_id,kind,title,body,created_at,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[id(),uid,kind,title,body,Date.now(),Date.now()+ttl]);}
export async function flag(q:Query,key:string){return (await q.one<{enabled:boolean}>('SELECT enabled FROM feature_flags WHERE key=$1',[key]))?.enabled||false;}
export async function activities(q:Query):Promise<Activity[]>{const rows=await q.all<{id:string;label:string;emoji:string;family:string;compatible:string[];options:Activity['options'];enabled:boolean;min_minutes:number}>('SELECT * FROM activities WHERE enabled=true ORDER BY id');return rows.map(r=>({...r,options:r.options?.length?r.options:(activityOptions[r.id]||[]).map(([id,label,emoji])=>({id,label,emoji})),minMinutes:r.min_minutes}));}
export async function profile(q:Query,uid:string):Promise<UserView>{const u=requireValue(await q.one<User>('SELECT * FROM users WHERE id=$1',[uid]));const r=await q.one<{accepted:number;attended:number;late_cancels:number}>('SELECT * FROM reliability_profiles WHERE user_id=$1',[uid]);const prefs=(await q.one<PrefRow>('SELECT * FROM preferences WHERE user_id=$1',[uid]))?.data||defaultPreferences;const communities=await q.all<{id:string;name:string;verified:boolean}>('SELECT c.id,c.name,m.verified FROM communities c JOIN memberships m ON c.id=m.community_id WHERE m.user_id=$1',[uid]);const consents=await q.all<{purpose:string;granted:boolean}>('SELECT purpose,granted FROM consents WHERE user_id=$1 ORDER BY created_at',[uid]);return {id:u.id,displayName:u.display_name,username:u.username,avatar:u.avatar,avatarPending:!!u.avatar_pending,country:u.country,ageStatus:u.age_status,trust:u.trust,role:u.role,isDemo:u.is_demo,reliability:{score:reliability(r?.attended||0,r?.accepted||0,r?.late_cancels||0),attended:r?.attended||0,accepted:r?.accepted||0},preferences:{...defaultPreferences,...prefs},communities,consents:Object.fromEntries(consents.map(c=>[c.purpose,c.granted]))};}
export async function rate(q:Query,key:string,limit:number,windowMs:number){const now=Date.now();await q.exec('INSERT INTO rate_buckets(key,hits,resets_at) VALUES($1,1,$2) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN rate_buckets.resets_at<$3 THEN 1 ELSE rate_buckets.hits+1 END,resets_at=CASE WHEN rate_buckets.resets_at<$3 THEN $2 ELSE rate_buckets.resets_at END',[hash(key),now+windowMs,now]);const row=await q.one<{hits:number}>('SELECT hits FROM rate_buckets WHERE key=$1',[hash(key)]);return (row?.hits||0)<=limit;}
export async function limited(db:Database,key:string,limit:number,windowMs:number){if(!await db.tx(q=>rate(q,key,limit,windowMs)))throw new ApiError('RATE_LIMIT','Dale un momento. Prueba de nuevo más tarde.',429);}
export async function idempotent<T>(q:Query,uid:string,key:string|undefined,scope:string,payload:unknown,fn:()=>Promise<T>):Promise<T>{if(!key||key.length<8||key.length>100)throw new ApiError('IDEMPOTENCY_REQUIRED','Falta el identificador de la operación.');const fingerprint=hash(JSON.stringify(payload));const prior=await q.one<{hash:string;result:T;expires_at:number}>('SELECT hash,result,expires_at FROM idempotency WHERE user_id=$1 AND key=$2 AND scope=$3',[uid,key,scope]);if(prior&&Number(prior.expires_at)>Date.now()){if(prior.hash!==fingerprint)throw new ApiError('IDEMPOTENCY_CONFLICT','Esta operación ya se utilizó con otros datos.',409);return prior.result;}const result=await fn();await q.exec('INSERT INTO idempotency VALUES($1,$2,$3,$4,$5::jsonb,$6) ON CONFLICT(user_id,key,scope) DO UPDATE SET hash=$4,result=$5::jsonb,expires_at=$6',[uid,key,scope,fingerprint,JSON.stringify(result),Date.now()+86400000]);return result;}
export const preferenceKeys: (keyof Preferences)[]=['notifications','liquidity','quietStart','quietEnd','timezone','radius','analytics'];
