import nodemailer from 'nodemailer';
import { createRemoteJWKSet,jwtVerify } from 'jose';
import { ApiError } from '../../../packages/types/src/index';
import { env } from './env';
export interface MailProvider{sendCode(email:string,code:string):Promise<void>}
export const mail:MailProvider={async sendCode(email,code){if(env.demo)return;if(!process.env.SMTP_URL)throw new ApiError('MAIL_UNAVAILABLE','El correo todavía no está configurado.',503);await nodemailer.createTransport(process.env.SMTP_URL).sendMail({from:process.env.MAIL_FROM,to:email,subject:'Tu código de acceso a NOW',text:`Tu código es ${code}. Caduca en 10 minutos. Si no lo has solicitado, ignora este mensaje.`});}};
export interface AgeVerificationProvider{verify(proof:string,userId:string):Promise<{over18:boolean;assurance:string;reference:string;expiresAt:number}>}
export const ageProvider:AgeVerificationProvider={async verify(proof,userId){if(env.demo&&proof==='DEMO-OVER18')return {over18:true,assurance:'demo',reference:'synthetic',expiresAt:Date.now()+86400000};if(!process.env.AGE_PROVIDER_URL||!process.env.AGE_PROVIDER_KEY)throw new ApiError('AGE_PROVIDER_UNAVAILABLE','La verificación reforzada aún no está disponible.',503);const r=await fetch(process.env.AGE_PROVIDER_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${process.env.AGE_PROVIDER_KEY}`},body:JSON.stringify({proof,subject:userId}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw new ApiError('AGE_INVALID','No pudimos validar la prueba de edad.',422);const data=await r.json() as Record<string,unknown>;if(data.over18!==true||typeof data.reference!=='string'||typeof data.expiresAt!=='number'||data.expiresAt<Date.now()||data.subject!==userId)throw new ApiError('AGE_INVALID','La prueba de edad no es válida.',422);return {over18:true,assurance:'verified',reference:data.reference,expiresAt:data.expiresAt};}};
export interface IdentityProvider{verify(idToken:string,nonce:string):Promise<{email:string;subject:string}>}
export function identityProvider(provider:'google'|'apple'):IdentityProvider{return {async verify(idToken,nonce){const audiences=(provider==='google'?process.env.GOOGLE_CLIENT_ID:process.env.APPLE_CLIENT_ID)?.split(',').map(x=>x.trim()).filter(Boolean)||[];if(!audiences.length)throw new ApiError('PROVIDER_UNAVAILABLE','Este proveedor no está conectado.',503);const issuer=provider==='google'?'https://accounts.google.com':'https://appleid.apple.com';const keys=createRemoteJWKSet(new URL(provider==='google'?'https://www.googleapis.com/oauth2/v3/certs':'https://appleid.apple.com/auth/keys'));const {payload}=await jwtVerify(idToken,keys,{issuer,audience:audiences,algorithms:['RS256','ES256']});if(payload.nonce!==nonce||!(payload.email_verified===true||payload.email_verified==='true')||typeof payload.email!=='string'||!payload.sub)throw new ApiError('IDENTITY_INVALID','La identidad no pudo verificarse.',401);return {email:payload.email.toLowerCase(),subject:payload.sub};}};}
export interface PushProvider{send(token:string,title:string,body:string):Promise<void>}
export const push:PushProvider={async send(token,title,body){if(env.demo||process.env.PUSH_PROVIDER!=='expo')return;const r=await fetch('https://exp.host/--/api/v2/push/send',{method:'POST',headers:{'Content-Type':'application/json',...(process.env.EXPO_ACCESS_TOKEN?{Authorization:`Bearer ${process.env.EXPO_ACCESS_TOKEN}`}:{})},body:JSON.stringify({to:token,title,body,sound:'default'}),signal:AbortSignal.timeout(10000)});const payload=await r.json() as {data?:{status?:string}};if(!r.ok||payload.data?.status==='error')throw new Error('push_delivery_failed');}};
export interface StorageProvider{put(key:string,bytes:Uint8Array,mime:string):Promise<string>;remove(key:string):Promise<void>}
/** Avatars intentionally use initials in V1; uploads stay closed until EXIF stripping and moderation are configured. */
export interface AnalyticsProvider{track(event:{name:string;activity?:string;city?:string;value?:number}):Promise<void>}
export const localAnalytics:AnalyticsProvider={async track(event){console.info(JSON.stringify({event:'analytics',...event}));}};
