import type { Database,Query } from '../../../db/client';
import { type z } from 'zod';
import { type reportInput,ApiError } from '../../../packages/types/src/index';
import { config } from '../../../packages/config/src/index';
import { id,hash } from './crypto';
import { active,audit,idempotent,metric,notify,requireValue } from './core';
import { MatchingService } from './matching';
export class SafetyService {
 constructor(public db:Database,public matches:MatchingService){}
 async context(q:Query,uid:string,target:string,mid?:string){if(uid===target)throw new ApiError('INVALID_TARGET','Selecciona otra persona.');if(mid){requireValue(await q.one('SELECT user_id FROM match_members WHERE match_id=$1 AND user_id=$2',[mid,uid]));requireValue(await q.one('SELECT user_id FROM match_members WHERE match_id=$1 AND user_id=$2',[mid,target]));}else {const related=await q.one('SELECT a.user_id FROM match_members a JOIN match_members b ON a.match_id=b.match_id WHERE a.user_id=$1 AND b.user_id=$2 UNION SELECT a FROM friendships WHERE (a=$1 AND b=$2) OR (a=$2 AND b=$1) LIMIT 1',[uid,target]);requireValue(related);}}
 async block(uid:string,target:string){return this.db.tx(async q=>{await active(q,uid);await this.context(q,uid,target);await q.exec('INSERT INTO blocks VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[uid,target,Date.now()]);await q.exec('DELETE FROM friendships WHERE (a=$1 AND b=$2) OR (a=$2 AND b=$1)',[uid,target]);const shared=await q.all<{id:string}>('SELECT m.id FROM matches m JOIN match_members a ON a.match_id=m.id JOIN match_members b ON b.match_id=m.id WHERE a.user_id=$1 AND b.user_id=$2 AND m.state IN (\'PROPOSAL_PENDING\',\'PARTIALLY_ACCEPTED\',\'CONFIRMED\') AND a.safety_exit=false',[uid,target]);for(const m of shared)await this.matches.safeExit(q,uid,m.id);await q.exec('DELETE FROM notifications WHERE user_id=$1 AND kind=$2',[uid,'liquidity']);await audit(q,uid,'block.created',target);await metric(q,'block_created');return {ok:true};});}
 async report(uid:string,input:z.infer<typeof reportInput>,key?:string){return this.db.tx(async q=>{await active(q,uid);return idempotent(q,uid,key,'report',input,async()=>{await this.context(q,uid,input.subjectId,input.matchId);if(input.messageId)requireValue(await q.one('SELECT id FROM messages WHERE id=$1 AND match_id=$2 AND sender_id=$3',[input.messageId,input.matchId,input.subjectId]));const severity=['violence','underage','safety'].includes(input.category)?0:['harassment','discrimination'].includes(input.category)?1:input.category==='no_show'?3:2;const rid=id();await q.exec('INSERT INTO reports(id,reporter,subject,match_id,message_id,category,details,severity,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[rid,uid,input.subjectId,input.matchId||null,input.messageId||null,input.category,input.details,severity,Date.now()]);await audit(q,uid,'report.created',rid,{severity});await metric(q,'report_created');await notify(q,uid,'safety','Hemos recibido tu reporte','Puedes bloquear a la persona y abandonar el encuentro en cualquier momento.');return {id:rid,state:'open'};});});}
 async deleteAccount(uid:string){return this.db.tx(async q=>{const current=await q.all<{id:string}>('SELECT m.id FROM matches m JOIN match_members mm ON mm.match_id=m.id WHERE mm.user_id=$1 AND mm.safety_exit=false AND m.state IN (\'PROPOSAL_PENDING\',\'PARTIALLY_ACCEPTED\',\'CONFIRMED\')',[uid]);for(const m of current)await this.matches.safeExit(q,uid,m.id);await q.exec('DELETE FROM sessions WHERE user_id=$1',[uid]);await q.exec('DELETE FROM auth_challenges WHERE email IN (SELECT email FROM identity.contacts WHERE user_id=$1)',[uid]);await q.exec('DELETE FROM identity.contacts WHERE user_id=$1',[uid]);for(const table of ['preferences','memberships','devices','consents','idempotency','age_verifications','reliability_profiles','reliability_events','attendance','notifications'])await q.exec(`DELETE FROM ${table} WHERE user_id=$1`,[uid]);await q.exec('DELETE FROM invitations WHERE user_id=$1 OR used_by=$1',[uid]);await q.exec('DELETE FROM friendships WHERE a=$1 OR b=$1',[uid]);await q.exec('DELETE FROM blocks WHERE blocker=$1 OR blocked=$1',[uid]);await q.exec('UPDATE reports SET message_id=NULL WHERE message_id IN (SELECT id FROM messages WHERE sender_id=$1)',[uid]);await q.exec('DELETE FROM messages WHERE sender_id=$1',[uid]);await q.exec('UPDATE match_members SET feedback=NULL WHERE user_id=$1',[uid]);await q.exec('UPDATE intents SET lat=NULL,lon=NULL,cell_x=NULL,cell_y=NULL,status=$1 WHERE user_id=$2',['CANCELLED',uid]);await q.exec('UPDATE match_members SET intent_id=NULL WHERE user_id=$1',[uid]);await q.exec('DELETE FROM intents WHERE user_id=$1',[uid]);await q.exec('UPDATE users SET display_name=$1,username=$2,avatar=NULL,avatar_pending=NULL,avatar_pending_at=NULL,status=$3,over18=false,trust=$4,age_status=$5,updated_at=$6 WHERE id=$7',['Cuenta eliminada','deleted_'+hash(uid).slice(0,16),'deleted','none','deleted',Date.now(),uid]);await audit(q,null,'account.deleted',uid,{retention:'Safety records restricted; max 180 days after resolution unless reviewed hold.'});return {ok:true,message:'Cuenta eliminada y sesiones revocadas. Los expedientes de seguridad se conservan según la política indicada.'};});}
 async export(uid:string){return this.db.tx(async q=>{const data:Record<string,unknown>={generatedAt:new Date().toISOString()};for(const table of ['users','identity.contacts','preferences','memberships','age_verifications','reliability_profiles','consents','devices','notifications','attendance','reliability_events']){const fields=table==='devices'?'id,platform,created_at':'*';data[table]=await q.all(`SELECT ${fields} FROM ${table} WHERE ${table==='users'?'id':'user_id'}=$1`,[uid]);}data.intents=await q.all('SELECT id,activity,start_at,end_at,status,visibility,radius FROM intents WHERE user_id=$1',[uid]);data.messages=await q.all('SELECT id,match_id,body,created_at FROM messages WHERE sender_id=$1',[uid]);data.reports=await q.all('SELECT id,category,details,state,created_at FROM reports WHERE reporter=$1',[uid]);data.sessions=await q.all('SELECT id,device_name,created_at,expires_at,revoked FROM sessions WHERE user_id=$1',[uid]);data.friends=await q.all('SELECT a,b,status FROM friendships WHERE a=$1 OR b=$1',[uid]);data.blocks=await q.all('SELECT blocked,created_at FROM blocks WHERE blocker=$1',[uid]);data.matches=await q.all('SELECT m.id,m.activity,m.state,m.scheduled_at,m.ends_at,mm.response,mm.checked_in FROM matches m JOIN match_members mm ON mm.match_id=m.id WHERE mm.user_id=$1',[uid]);await audit(q,uid,'privacy.export');return data;});}
 async retention(){await this.db.tx(async q=>{const now=Date.now();await q.exec('UPDATE users SET interest_cell_x=NULL,interest_cell_y=NULL,interest_location_expires_at=NULL WHERE interest_location_expires_at<=$1',[now]);await q.exec('DELETE FROM messages WHERE expires_at<$1 AND id NOT IN (SELECT message_id FROM reports WHERE message_id IS NOT NULL AND state<>$2)',[now,'resolved']);await q.exec('DELETE FROM auth_challenges WHERE expires_at<$1',[now]);await q.exec('DELETE FROM sessions WHERE expires_at<$1',[now]);await q.exec('DELETE FROM idempotency WHERE expires_at<$1',[now]);await q.exec('DELETE FROM invitations WHERE expires_at<$1',[now]);await q.exec('DELETE FROM rate_buckets WHERE resets_at<$1',[now]);await q.exec('DELETE FROM notifications WHERE created_at<$1',[now-config.notificationRetentionDays*86400000]);await q.exec('DELETE FROM analytics_events WHERE created_at<$1',[now-config.analyticsRetentionDays*86400000]);await q.exec('DELETE FROM audit_events WHERE created_at<$1',[now-config.auditRetentionDays*86400000]);await q.exec('UPDATE match_members SET intent_id=NULL WHERE intent_id IN (SELECT id FROM intents WHERE created_at<$1 AND status NOT IN (\'SEARCHING\',\'RESERVED\'))',[now-config.intentRetentionDays*86400000]);await q.exec('DELETE FROM intents WHERE created_at<$1 AND status NOT IN (\'SEARCHING\',\'RESERVED\')',[now-config.intentRetentionDays*86400000]);await q.exec('UPDATE reports SET details=$1 WHERE state=$2 AND resolved_at<$3',['Contenido eliminado por retención','resolved',now-config.reportRetentionDays*86400000]);});}
}
